# Sample workflow for building and deploying a Next.js site to GitHub Pages
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Set the appropriate Node.js version here

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
          else
            echo "manager=npm" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: ${{ env.manager }} install

      - name: Build with Next.js
        run: ${{ env.manager }} run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-app
          path: .next

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: nextjs-app
          path: .next

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # Set your target branch for GitHub Pages deployment
          FOLDER: .next # Set the folder containing your static assets
          CLEAN: true
